export const FETCH_USERS = 'FETCH_USERS'
export const SEARCH_USERS = 'SEARCH_USERS'
export const FETCH_USER = 'FETCH_USER'
export const IS_LOADING = 'IS_LOADING'
export const SWITCH_PAGE = 'SWITCH_PAGE'
